### ISSUE TITLE
Finish a game when player cannot move any piece 

### ISSUE THREAD

**Issue by zodo** [m0ksem/GameCheckersBot#2]
The game doesn't support the case when player still have a few pieces but cannot move them. See screenshot
![Screenshot_20200324-192308_Telegram X](https://user-images.githubusercontent.com/9845592/77426052-4c77cc00-6e06-11ea-8b9a-0cccd34ff1c2.jpg)

Black should win here

**Comment by m0ksem** [comment]
Fixed in version 2.0 in private repository. Thank you.
