### ISSUE TITLE
Uzbek

### ISSUE THREAD

**Issue by Muhammadbobur40** [m0ksem/GameCheckersBot#32]
**Check example**

The language for the bot must be provided in JSON format.

[English](https://github.com/m0ksem/GameCheckersBot/blob/master/src/dictionary/langs/en.json)

[Russian](https://github.com/m0ksem/GameCheckersBot/blob/master/src/dictionary/langs/ru.json)

**Comment by m0ksem** [comment]
Visit [Translation app](https://m0ksem.github.io/translations/?project=GameCheckersBot) and submit your translation.
