### ISSUE TITLE
spanish

### ISSUE THREAD

**Issue by MGL22** [m0ksem/GameCheckersBot#62]
**Check example**

The language for the bot must be provided in JSON format.

[English](https://github.com/m0ksem/GameCheckersBot/blob/master/src/dictionary/langs/en.json)

[Russian](https://github.com/m0ksem/GameCheckersBot/blob/master/src/dictionary/langs/ru.json)

**Comment by MGL22** [comment]
Sorry I didn't mean to open an issue I wanted to add spanish language to checkers bot but I don't now how. I don't know where find sp.json file or something like this.
If somebody could  tell me how I can  do this I would be grateful

**Comment by MGL22** [comment]
Thanks but as I said " I don't know where find sp.json file or something like this." and I'm not a programer If you were so kind to give me some guidance to find this sp.json or how I can create it 
I want to contribute but sadly my skills are poor at the moment
Thanks

**Comment by m0ksem** [comment]
1. You need to make a fork. You can read about it https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#fork-an-example-repository
2. You need a simple to create a file with the name `sp.json` (like `sp.txt`, but `sp.json`) in following path `/src/dictionary/langs`
3. You can copy content from `en.json`, paste it to `sp.json` and translate English strings to Spanish.

You need to translate exactly strings in a second ""
![image](https://user-images.githubusercontent.com/23530004/118273620-d1bbb580-b4cc-11eb-8d1a-a60dc887f64e.png)

So the result should be:
```
{
  "langName": "Spanish",
  "langCode": "sp",
  ... 
```

Then you need to go to the Open Pull Request tab in your fork and make a new pull request. I will review it and apply it to production.

There is no program with an interface for editing languages. You need to change `.json` files as text in notepad or smth else.

**Comment by MGL22** [comment]
Thanks I'll try

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by m0ksem** [comment]
Visit [Translation app](https://m0ksem.github.io/translations/?project=GameCheckersBot) and submit your translation.
