### ISSUE TITLE
Where is UKRAINE language?

### ISSUE THREAD

**Issue by Asculapa** [m0ksem/GameCheckersBot#94]
Хлопче, а чи не забули Ви добавити нашу рідну мову?

**Comment by m0ksem** [comment]
Please, provide the `ua.json` file with your translation to `/src/dictionary/langs/` via Pull Request.

**Comment by m0ksem** [comment]
Visit [Translation app](https://m0ksem.github.io/translations/?project=GameCheckersBot) and submit your translation.
